/**
 * County Branding Service
 * Applies county-specific headers, footers, and styling to generated PDFs
 */

import PDFDocument from 'pdfkit';
import tampaConfig from '../config/counties/hillsborough';

export interface CountyConfig {
  name: string;
  county: string;
  header: string;
  contact: {
    address: string;
    phone: string;
    website: string;
  };
}

/**
 * Get county configuration by name
 */
export function getCountyConfig(county: string): CountyConfig {
  // Normalize county name
  const normalizedCounty = county.toLowerCase().trim();

  switch (normalizedCounty) {
    case 'hillsborough':
    case 'tampa':
      return {
        name: 'City of Tampa',
        county: 'Hillsborough',
        header: 'CITY OF TAMPA\nDEPARTMENT OF CONSTRUCTION SERVICES',
        contact: {
          address: '306 East Jackson Street, Tampa, FL 33602',
          phone: '(813) 274-8211',
          website: 'tampa.gov/construction-services',
        },
      };

    case 'pinellas':
      return {
        name: 'Pinellas County',
        county: 'Pinellas',
        header: 'PINELLAS COUNTY\nCONSTRUCTION SERVICES',
        contact: {
          address: '400 S. Fort Harrison Ave, Clearwater, FL 33756',
          phone: '(727) 464-4062',
          website: 'pinellas.gov/permits',
        },
      };

    case 'pasco':
      return {
        name: 'Pasco County',
        county: 'Pasco',
        header: 'PASCO COUNTY\nCONSTRUCTION SERVICES',
        contact: {
          address: '8731 Citizens Dr, New Port Richey, FL 34654',
          phone: '(727) 847-2411',
          website: 'pascocountyfl.net/permits',
        },
      };

    default:
      // Default to Tampa/Hillsborough
      return {
        name: 'City of Tampa',
        county: 'Hillsborough',
        header: 'CITY OF TAMPA\nDEPARTMENT OF CONSTRUCTION SERVICES',
        contact: {
          address: '306 East Jackson Street, Tampa, FL 33602',
          phone: '(813) 274-8211',
          website: 'tampa.gov/construction-services',
        },
      };
  }
}

/**
 * Apply county branding to PDF document
 * Adds header, footer, and county-specific styling
 *
 * @param doc - PDFKit document instance
 * @param county - County name (e.g., 'hillsborough', 'tampa')
 * @param options - Optional branding options
 */
export function applyCountyBranding(
  doc: typeof PDFDocument,
  county: string,
  options: {
    includeHeader?: boolean;
    includeFooter?: boolean;
    headerY?: number;
    footerY?: number;
  } = {}
): void {
  const config = getCountyConfig(county);
  const {
    includeHeader = true,
    includeFooter = true,
    headerY = 50,
    footerY = doc.page.height - 50,
  } = options;

  // Apply header
  if (includeHeader) {
    addHeader(doc, config, headerY);
  }

  // Apply footer
  if (includeFooter) {
    addFooter(doc, config, footerY);
  }
}

/**
 * Add county header to PDF
 */
function addHeader(doc: typeof PDFDocument, config: CountyConfig, y: number): void {
  const pageWidth = doc.page.width;
  const centerX = pageWidth / 2;

  // Save current position
  const currentY = doc.y;

  // Draw header
  doc
    .fontSize(10)
    .font('Helvetica-Bold')
    .text(config.header, 50, y, {
      width: pageWidth - 100,
      align: 'center',
    });

  // Add horizontal line below header
  const headerHeight = doc.heightOfString(config.header, {
    width: pageWidth - 100,
  });
  const lineY = y + headerHeight + 5;

  doc
    .moveTo(50, lineY)
    .lineTo(pageWidth - 50, lineY)
    .stroke('#333333');

  // Restore font
  doc.fontSize(10).font('Helvetica');

  // Move cursor below header
  if (currentY < lineY + 10) {
    doc.y = lineY + 15;
  }
}

/**
 * Add county footer to PDF
 */
function addFooter(doc: typeof PDFDocument, config: CountyConfig, y: number): void {
  const pageWidth = doc.page.width;

  // Save current settings
  const currentFontSize = 10;

  // Draw horizontal line above footer
  doc
    .moveTo(50, y - 10)
    .lineTo(pageWidth - 50, y - 10)
    .stroke('#cccccc');

  // Add footer text
  doc
    .fontSize(8)
    .font('Helvetica')
    .fillColor('#666666')
    .text(
      `${config.name} • ${config.contact.address}`,
      50,
      y,
      {
        width: pageWidth - 100,
        align: 'center',
      }
    );

  doc
    .fontSize(8)
    .text(
      `Phone: ${config.contact.phone} • Web: ${config.contact.website}`,
      50,
      y + 12,
      {
        width: pageWidth - 100,
        align: 'center',
      }
    );

  // Reset font and color
  doc.fontSize(currentFontSize).font('Helvetica').fillColor('#000000');
}

/**
 * Add "Generated by AI-Permit-Tampa" attribution
 */
export function addAIAttribution(doc: typeof PDFDocument): void {
  const pageWidth = doc.page.width;
  const y = doc.page.height - 25;

  doc
    .fontSize(7)
    .font('Helvetica')
    .fillColor('#999999')
    .text(
      'Generated by AI-Permit-Tampa • Automated Permit Document Service',
      50,
      y,
      {
        width: pageWidth - 100,
        align: 'center',
      }
    );

  // Reset font and color
  doc.fontSize(10).font('Helvetica').fillColor('#000000');
}

/**
 * Create a branded page with header and footer pre-applied
 * Use this for starting new pages in multi-page documents
 */
export function createBrandedPage(
  doc: typeof PDFDocument,
  county: string
): void {
  doc.addPage();
  applyCountyBranding(doc, county, {
    includeHeader: true,
    includeFooter: true,
  });

  // Set starting Y position below header
  doc.y = 100;
}

/**
 * Apply branding to all pages in document
 * Call this at the end of document generation
 */
export function brandAllPages(
  doc: typeof PDFDocument,
  county: string,
  totalPages: number
): void {
  const config = getCountyConfig(county);

  // Note: PDFKit doesn't support easy page iteration after generation
  // This function is a placeholder for future enhancement
  // For now, branding should be applied during page creation

  // Alternative approach: Use page events (if available in PDFKit)
  // Or apply branding when each page is created
}

export default {
  getCountyConfig,
  applyCountyBranding,
  addAIAttribution,
  createBrandedPage,
  brandAllPages,
};
